### ISSUE TITLE
Add m3u file

### ISSUE THREAD

**Issue by Tricky12321** [jellyfin/jellyfin-plugin-iptv#7]
Is there an option to import a m3u file?

**Comment by anthonylavado** [comment]
Yes, and you don’t even have to use this plugin.

In your Jellyfin dashboard, locate the Live TV settings. Add a new tuner, of type M3U tuner, and you should be set.

**Edit**
This won’t import it per se (it will have to exist somewhere, like online or in a folder), but it will enable it in Jellyfin.

**Comment by Tricky12321** [comment]
Works
